// <auto-generated />
using System;
using Churritos.Dominio.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Churritos.Dominio.Migrations
{
    [DbContext(typeof(ContextoDaAplicação))]
    [Migration("20200422041033_SeedInicial")]
    partial class SeedInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Churritos.Dominio.Modelos.Cobertura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cobertura");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Confete"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Coco"
                        });
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.EntidadesAuxiliares.TipoItemCobertura", b =>
                {
                    b.Property<int?>("TipoItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoberturaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoItemId", "CoberturaId");

                    b.HasIndex("CoberturaId");

                    b.ToTable("TipoItemCobertura");
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.EntidadesAuxiliares.TipoItemRecheio", b =>
                {
                    b.Property<int?>("TipoItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecheioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoItemId", "RecheioId");

                    b.HasIndex("RecheioId");

                    b.ToTable("TipoItemRecheio");
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TipoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoberturaSelecionadaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecheioSelecionadoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoberturaSelecionadaId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("RecheioSelecionadoId");

                    b.ToTable("ItemPedido");
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriação")
                        .HasColumnName("DataCriacao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.Recheio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recheio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Doce de leite"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Chocolate"
                        });
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.TipoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TipoItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Doces Tradicionais"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Doces Especiais"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Doces Gelados"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Salgados"
                        });
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.EntidadesAuxiliares.TipoItemCobertura", b =>
                {
                    b.HasOne("Churritos.Dominio.Modelos.Cobertura", null)
                        .WithMany()
                        .HasForeignKey("CoberturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Churritos.Dominio.Modelos.TipoItem", null)
                        .WithMany("_tipoItemCoberturas")
                        .HasForeignKey("TipoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.EntidadesAuxiliares.TipoItemRecheio", b =>
                {
                    b.HasOne("Churritos.Dominio.Modelos.Recheio", null)
                        .WithMany()
                        .HasForeignKey("RecheioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Churritos.Dominio.Modelos.TipoItem", null)
                        .WithMany("_tipoItemRecheios")
                        .HasForeignKey("TipoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.Item", b =>
                {
                    b.HasOne("Churritos.Dominio.Modelos.TipoItem", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId");
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.ItemPedido", b =>
                {
                    b.HasOne("Churritos.Dominio.Modelos.Cobertura", "CoberturaSelecionada")
                        .WithMany()
                        .HasForeignKey("CoberturaSelecionadaId");

                    b.HasOne("Churritos.Dominio.Modelos.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Churritos.Dominio.Modelos.Pedido", null)
                        .WithMany("_itens")
                        .HasForeignKey("PedidoId");

                    b.HasOne("Churritos.Dominio.Modelos.Recheio", "RecheioSelecionado")
                        .WithMany()
                        .HasForeignKey("RecheioSelecionadoId");
                });
#pragma warning restore 612, 618
        }
    }
}
