// <auto-generated />
using System;
using Churritos.Dominio.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Churritos.Dominio.Migrations
{
    [DbContext(typeof(ContextoDaAplicação))]
    [Migration("20200529032650_SeedProdutosComRecheiosECoberturas")]
    partial class SeedProdutosComRecheiosECoberturas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Churritos.Dominio.Modelos.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Doces Tradicionais"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Doces Especiais"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Doces Gelados"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Salgados"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Salgados Especiais"
                        });
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.Cobertura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cobertura");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Coco"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Confete"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Granulado"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Granulado colorido"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Choco ball"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Amendoim moído"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Oreo"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Kit kat preto"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Kit kat branco"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Ouro branco"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Sonho de valsa"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Ovomantine"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Ninho em pó"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Morango"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Banana"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Cheddar"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Catupiry"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Cream cheese"
                        });
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.EntidadesAuxiliares.ProdutoCobertura", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoberturaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProdutoId", "CoberturaId");

                    b.HasIndex("CoberturaId");

                    b.ToTable("ProdutoCobertura");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 1
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 2
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 3
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 4
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 5
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 6
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 7
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 8
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 9
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 10
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 11
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 12
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 13
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 14
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 15
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 16
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 17
                        },
                        new
                        {
                            ProdutoId = 1,
                            CoberturaId = 18
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 1
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 2
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 3
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 4
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 5
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 6
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 7
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 8
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 9
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 10
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 11
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 12
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 13
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 14
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 15
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 16
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 17
                        },
                        new
                        {
                            ProdutoId = 2,
                            CoberturaId = 18
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 1
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 2
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 3
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 4
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 5
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 6
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 7
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 8
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 9
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 10
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 11
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 12
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 13
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 14
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 15
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 16
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 17
                        },
                        new
                        {
                            ProdutoId = 3,
                            CoberturaId = 18
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 1
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 2
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 3
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 4
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 5
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 6
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 7
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 8
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 9
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 10
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 11
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 12
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 13
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 14
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 15
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 16
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 17
                        },
                        new
                        {
                            ProdutoId = 4,
                            CoberturaId = 18
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 1
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 2
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 3
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 4
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 5
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 6
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 7
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 8
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 9
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 10
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 11
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 12
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 13
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 14
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 15
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 16
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 17
                        },
                        new
                        {
                            ProdutoId = 5,
                            CoberturaId = 18
                        });
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.EntidadesAuxiliares.ProdutoRecheio", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecheioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProdutoId", "RecheioId");

                    b.HasIndex("RecheioId");

                    b.ToTable("ProdutoRecheio");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            RecheioId = 1
                        },
                        new
                        {
                            ProdutoId = 1,
                            RecheioId = 2
                        },
                        new
                        {
                            ProdutoId = 1,
                            RecheioId = 3
                        },
                        new
                        {
                            ProdutoId = 1,
                            RecheioId = 4
                        },
                        new
                        {
                            ProdutoId = 1,
                            RecheioId = 5
                        },
                        new
                        {
                            ProdutoId = 1,
                            RecheioId = 6
                        },
                        new
                        {
                            ProdutoId = 1,
                            RecheioId = 7
                        },
                        new
                        {
                            ProdutoId = 1,
                            RecheioId = 8
                        },
                        new
                        {
                            ProdutoId = 1,
                            RecheioId = 9
                        },
                        new
                        {
                            ProdutoId = 1,
                            RecheioId = 10
                        },
                        new
                        {
                            ProdutoId = 1,
                            RecheioId = 11
                        },
                        new
                        {
                            ProdutoId = 1,
                            RecheioId = 12
                        },
                        new
                        {
                            ProdutoId = 2,
                            RecheioId = 1
                        },
                        new
                        {
                            ProdutoId = 2,
                            RecheioId = 2
                        },
                        new
                        {
                            ProdutoId = 2,
                            RecheioId = 3
                        },
                        new
                        {
                            ProdutoId = 2,
                            RecheioId = 4
                        },
                        new
                        {
                            ProdutoId = 2,
                            RecheioId = 5
                        },
                        new
                        {
                            ProdutoId = 2,
                            RecheioId = 6
                        },
                        new
                        {
                            ProdutoId = 2,
                            RecheioId = 7
                        },
                        new
                        {
                            ProdutoId = 2,
                            RecheioId = 8
                        },
                        new
                        {
                            ProdutoId = 2,
                            RecheioId = 9
                        },
                        new
                        {
                            ProdutoId = 2,
                            RecheioId = 10
                        },
                        new
                        {
                            ProdutoId = 2,
                            RecheioId = 11
                        },
                        new
                        {
                            ProdutoId = 2,
                            RecheioId = 12
                        },
                        new
                        {
                            ProdutoId = 3,
                            RecheioId = 1
                        },
                        new
                        {
                            ProdutoId = 3,
                            RecheioId = 2
                        },
                        new
                        {
                            ProdutoId = 3,
                            RecheioId = 3
                        },
                        new
                        {
                            ProdutoId = 3,
                            RecheioId = 4
                        },
                        new
                        {
                            ProdutoId = 3,
                            RecheioId = 5
                        },
                        new
                        {
                            ProdutoId = 3,
                            RecheioId = 6
                        },
                        new
                        {
                            ProdutoId = 3,
                            RecheioId = 7
                        },
                        new
                        {
                            ProdutoId = 3,
                            RecheioId = 8
                        },
                        new
                        {
                            ProdutoId = 3,
                            RecheioId = 9
                        },
                        new
                        {
                            ProdutoId = 3,
                            RecheioId = 10
                        },
                        new
                        {
                            ProdutoId = 3,
                            RecheioId = 11
                        },
                        new
                        {
                            ProdutoId = 3,
                            RecheioId = 12
                        },
                        new
                        {
                            ProdutoId = 4,
                            RecheioId = 1
                        },
                        new
                        {
                            ProdutoId = 4,
                            RecheioId = 2
                        },
                        new
                        {
                            ProdutoId = 4,
                            RecheioId = 3
                        },
                        new
                        {
                            ProdutoId = 4,
                            RecheioId = 4
                        },
                        new
                        {
                            ProdutoId = 4,
                            RecheioId = 5
                        },
                        new
                        {
                            ProdutoId = 4,
                            RecheioId = 6
                        },
                        new
                        {
                            ProdutoId = 4,
                            RecheioId = 7
                        },
                        new
                        {
                            ProdutoId = 4,
                            RecheioId = 8
                        },
                        new
                        {
                            ProdutoId = 4,
                            RecheioId = 9
                        },
                        new
                        {
                            ProdutoId = 4,
                            RecheioId = 10
                        },
                        new
                        {
                            ProdutoId = 4,
                            RecheioId = 11
                        },
                        new
                        {
                            ProdutoId = 4,
                            RecheioId = 12
                        },
                        new
                        {
                            ProdutoId = 5,
                            RecheioId = 1
                        },
                        new
                        {
                            ProdutoId = 5,
                            RecheioId = 2
                        },
                        new
                        {
                            ProdutoId = 5,
                            RecheioId = 3
                        },
                        new
                        {
                            ProdutoId = 5,
                            RecheioId = 4
                        },
                        new
                        {
                            ProdutoId = 5,
                            RecheioId = 5
                        },
                        new
                        {
                            ProdutoId = 5,
                            RecheioId = 6
                        },
                        new
                        {
                            ProdutoId = 5,
                            RecheioId = 7
                        },
                        new
                        {
                            ProdutoId = 5,
                            RecheioId = 8
                        },
                        new
                        {
                            ProdutoId = 5,
                            RecheioId = 9
                        },
                        new
                        {
                            ProdutoId = 5,
                            RecheioId = 10
                        },
                        new
                        {
                            ProdutoId = 5,
                            RecheioId = 11
                        },
                        new
                        {
                            ProdutoId = 5,
                            RecheioId = 12
                        });
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriação")
                        .HasColumnName("DataCriacao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Nome = "Churros Doce Tradicional",
                            Valor = 8m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Nome = "Churros Doce Especial",
                            Valor = 12m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Nome = "Churros Doce Gelado",
                            Valor = 16m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            Nome = "Churros Salgado",
                            Valor = 10m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 5,
                            Nome = "Churros Salgado Especial",
                            Valor = 12m
                        });
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.ProdutoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoberturaSelecionadaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecheioSelecionadoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoberturaSelecionadaId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("RecheioSelecionadoId");

                    b.ToTable("ProdutoPedido");
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.Recheio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recheio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Doce de leite"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Chocolate"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Goiabada"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Misto"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Nutella"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Ninho"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Nutella com ninho"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Frango"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Calabresa"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Carne moída"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Carne seca"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Pizza"
                        });
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.EntidadesAuxiliares.ProdutoCobertura", b =>
                {
                    b.HasOne("Churritos.Dominio.Modelos.Cobertura", "Cobertura")
                        .WithMany()
                        .HasForeignKey("CoberturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Churritos.Dominio.Modelos.Produto", "Produto")
                        .WithMany("ProdutoCoberturas")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.EntidadesAuxiliares.ProdutoRecheio", b =>
                {
                    b.HasOne("Churritos.Dominio.Modelos.Produto", "Produto")
                        .WithMany("ProdutoRecheios")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Churritos.Dominio.Modelos.Recheio", "Recheio")
                        .WithMany()
                        .HasForeignKey("RecheioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.Produto", b =>
                {
                    b.HasOne("Churritos.Dominio.Modelos.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Churritos.Dominio.Modelos.ProdutoPedido", b =>
                {
                    b.HasOne("Churritos.Dominio.Modelos.Cobertura", "CoberturaSelecionada")
                        .WithMany()
                        .HasForeignKey("CoberturaSelecionadaId");

                    b.HasOne("Churritos.Dominio.Modelos.Pedido", null)
                        .WithMany("_produtos")
                        .HasForeignKey("PedidoId");

                    b.HasOne("Churritos.Dominio.Modelos.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.HasOne("Churritos.Dominio.Modelos.Recheio", "RecheioSelecionado")
                        .WithMany()
                        .HasForeignKey("RecheioSelecionadoId");
                });
#pragma warning restore 612, 618
        }
    }
}
